// Sample data for Nova Scotia gold mining locations
// This is placeholder data based on known gold districts in Nova Scotia
// Will be replaced with actual data from Nova Scotia Mineral Occurrence Database

const goldLocations = [
    {
        id: 1,
        name: "Goldenville Gold District",
        lat: 45.1481,
        lng: -61.9431,
        status: "historical",
        size: "large",
        discoveryYear: 1861,
        discoverer: "Nelson Nickerson",
        productionYears: "1862-1941",
        totalProduction: "209,383 troy oz.",
        description: "One of Nova Scotia's most productive gold districts, located in Guysborough County.",
        accessNotes: "Accessible via Route 7, then local roads. Some areas may be on private property."
    },
    {
        id: 2,
        name: "Goldboro Gold District",
        lat: 45.1823,
        lng: -61.6551,
        status: "active",
        size: "large",
        discoveryYear: 1861,
        discoverer: "Joseph Hynes",
        productionYears: "1862-1958",
        totalProduction: "131,728 troy oz.",
        description: "Major gold district with recent exploration activity.",
        accessNotes: "Some areas accessible via local roads, but active mining areas are restricted."
    },
    {
        id: 3,
        name: "Caribou Gold District",
        lat: 45.0474,
        lng: -62.0047,
        status: "historical",
        size: "medium",
        discoveryYear: 1864,
        discoverer: "Josiah Jennings",
        productionYears: "1869-1968",
        totalProduction: "91,336 troy oz.",
        description: "Historical gold district with significant past production.",
        accessNotes: "Accessible via local roads from Highway 7. Some areas may require permission."
    },
    {
        id: 4,
        name: "Oldham Gold District",
        lat: 44.9833,
        lng: -63.4500,
        status: "historical",
        size: "medium",
        discoveryYear: 1861,
        discoverer: "Edward Horne and Samuel Isner",
        productionYears: "1862-1946",
        totalProduction: "85,178 troy oz.",
        description: "Historical gold district near Halifax with rich history.",
        accessNotes: "Accessible from Highway 102, then local roads. Some areas on private property."
    },
    {
        id: 5,
        name: "Waverley Gold District",
        lat: 44.8333,
        lng: -63.6167,
        status: "historical",
        size: "medium",
        discoveryYear: 1861,
        discoverer: "Alexander Taylor",
        productionYears: "1862-1940",
        totalProduction: "72,567 troy oz.",
        description: "Historical gold district near Dartmouth with good accessibility.",
        accessNotes: "Easily accessible from Highway 118. Some areas may require permission."
    },
    {
        id: 6,
        name: "Montague Gold District",
        lat: 44.7167,
        lng: -63.5167,
        status: "historical",
        size: "medium",
        discoveryYear: 1860,
        discoverer: "Multiple discoverers",
        productionYears: "1863-1940",
        totalProduction: "65,197 troy oz.",
        description: "Historical gold district with good potential for panning.",
        accessNotes: "Accessible from Highway 107, then local roads. Check for private property."
    },
    {
        id: 7,
        name: "Tangier Gold District",
        lat: 44.7833,
        lng: -62.8833,
        status: "historical",
        size: "medium",
        discoveryYear: 1860,
        discoverer: "Peter Mason",
        productionYears: "1862-1919, 1986-1989, 1996-1997",
        totalProduction: "27,944 troy oz.",
        description: "One of the earliest discovered gold districts with recent activity.",
        accessNotes: "Accessible via Route 7, then local roads. Some areas may be on private property."
    },
    {
        id: 8,
        name: "Moose River Gold District",
        lat: 44.9833,
        lng: -62.9333,
        status: "active",
        size: "large",
        discoveryYear: 1866,
        discoverer: "John Pulsifer and Mr. Taylor",
        productionYears: "1888-1939",
        totalProduction: "25,917 troy oz.",
        description: "Site of the famous Moose River Mine Disaster of 1936, now with renewed mining interest.",
        accessNotes: "Accessible via local roads, but active mining areas are restricted."
    },
    {
        id: 9,
        name: "Mooseland Gold District",
        lat: 44.9500,
        lng: -62.9000,
        status: "historical",
        size: "small",
        discoveryYear: 1860,
        discoverer: "John Gerrish Pulsifer with Mi'kmaq guides",
        productionYears: "1863-1934",
        totalProduction: "3,865 troy oz.",
        description: "Historical gold district with Mi'kmaq connections.",
        accessNotes: "Accessible via local roads from Highway 7. Some areas may require permission."
    },
    {
        id: 10,
        name: "Wine Harbour Gold District",
        lat: 45.1167,
        lng: -61.7833,
        status: "historical",
        size: "medium",
        discoveryYear: 1860,
        discoverer: "Joseph Smith",
        productionYears: "1862-1939",
        totalProduction: "42,347 troy oz.",
        description: "Coastal gold district with interesting geology.",
        accessNotes: "Accessible via Route 316. Some areas may be on private property."
    },
    {
        id: 11,
        name: "Renfrew Gold District",
        lat: 44.8667,
        lng: -63.4500,
        status: "historical",
        size: "medium",
        discoveryYear: 1861,
        discoverer: "Multiple discoverers",
        productionYears: "1862-1958",
        totalProduction: "51,596 troy oz.",
        description: "Historical gold district with long production history.",
        accessNotes: "Accessible from Highway 102, then local roads. Check for private property."
    },
    {
        id: 12,
        name: "Fifteen Mile Stream",
        lat: 45.1167,
        lng: -62.0833,
        status: "active",
        size: "large",
        discoveryYear: 1867,
        discoverer: "Unknown",
        productionYears: "Historical and recent exploration",
        totalProduction: "Significant historical production",
        description: "Historical gold district with recent exploration activity.",
        accessNotes: "Remote location, accessible via logging roads. Some areas may be restricted."
    },
    {
        id: 13,
        name: "Forest Hill Gold District",
        lat: 45.2833,
        lng: -62.1167,
        status: "historical",
        size: "small",
        discoveryYear: 1893,
        discoverer: "Unknown",
        productionYears: "1893-1910",
        totalProduction: "Limited historical records",
        description: "Small historical gold district with potential for panning.",
        accessNotes: "Accessible via local roads. Some areas may require permission."
    },
    {
        id: 14,
        name: "Cochrane Hill",
        lat: 45.1833,
        lng: -61.9500,
        status: "active",
        size: "medium",
        discoveryYear: 1877,
        discoverer: "Unknown",
        productionYears: "Historical and recent exploration",
        totalProduction: "Significant historical production",
        description: "Historical gold district with recent exploration interest.",
        accessNotes: "Accessible via local roads from Highway 7. Some areas may be restricted."
    },
    {
        id: 15,
        name: "Beaver Dam",
        lat: 44.8833,
        lng: -62.7333,
        status: "active",
        size: "medium",
        discoveryYear: 1868,
        discoverer: "Unknown",
        productionYears: "Historical and recent exploration",
        totalProduction: "Significant historical production",
        description: "Historical gold district with recent development plans.",
        accessNotes: "Remote location, accessible via logging roads. Some areas may be restricted."
    }
];

// Export the data for use in map.js
// In a real application, this would be replaced with data loaded from the Nova Scotia Mineral Occurrence Database
